### ISSUE TITLE
archlight 1.20.1 1.0.6 error while start 

### ISSUE THREAD

**Issue by Lindsaydoodle** [Artillex-Studios/AxInventoryRestore#15]
[20:02:06 ERROR] [Minecraft]: Error occurred while enabling AxInventoryRestore v2.4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/h2/index/IndexCondition
        at org.h2.expression.condition.Comparison.createIndexConditions(Comparison.java:441) ~[?:?]
        at org.h2.expression.condition.Comparison.createIndexConditions(Comparison.java:392) ~[?:?]
        at org.h2.command.dml.Delete.doPrepare(Delete.java:114) ~[?:?]
        at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37) ~[?:?]
        at org.h2.command.Parser.prepareCommand(Parser.java:575) ~[?:?]
        at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631) ~[?:?]
        at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554) ~[?:?]
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116) ~[?:?]
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92) ~[?:?]
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288) ~[?:?]
        at com.artillexstudios.axinventoryrestore.libs.hikari.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327) ~[?:?]
        at com.artillexstudios.axinventoryrestore.libs.hikari.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[?:?]
        at com.artillexstudios.axinventoryrestore.database.impl.Base.cleanup(Base.java:397) ~[?:?]
        at com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:98) ~[?:?]
        at com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:90) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23270!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23270!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23270!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23270!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23270!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5]
        at net.minecraft.server.MinecraftServer.handler$bfe000$arclight$enablePlugins(MinecraftServerMixin.java:2138) ~[server-1.20.1-20230612.114412-srg.jar%23379!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385) ~[server-1.20.1-20230612.114412-srg.jar%23379!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23379!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23379!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2029) ~[server-1.20.1-20230612.114412-srg.jar%23379!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23379!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.h2.index.IndexCondition
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:147) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23270!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5.jar%23270!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 27 more

**Comment by BenceX100** [comment]
This is probably not a plugin issue. But either way, I will close this as it is very old, if it still happens, reopen it.
