### ISSUE TITLE
[Bug] Exception in thread "AxInventoryRestore-Datastore-thread" java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by darksaid98** [Artillex-Studios/AxInventoryRestore#2]
Using `mysql` for saving data. This issue occurs after:

```
darksaid98 issued server command: /axinventoryrestore darksaid98
```

```
[14:53:33 WARN]: Exception in thread "AxInventoryRestore-Datastore-thread" java.util.ConcurrentModificationException
[14:53:33 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
[14:53:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.persistence.CraftPersistentDataTypeRegistry.wrap(CraftPersistentDataTypeRegistry.java:212)
[14:53:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.persistence.CraftPersistentDataContainer.set(CraftPersistentDataContainer.java:41)
[14:53:33 WARN]:        at AxInventoryRestore-1.2.2.jar//com.artillexstudios.axinventoryrestore.libs.gui.components.nbt.Pdc.setString(Pdc.java:58)
[14:53:33 WARN]:        at AxInventoryRestore-1.2.2.jar//com.artillexstudios.axinventoryrestore.libs.gui.components.util.ItemNbt.setString(ItemNbt.java:49)
[14:53:33 WARN]:        at AxInventoryRestore-1.2.2.jar//com.artillexstudios.axinventoryrestore.libs.gui.guis.GuiItem.<init>(GuiItem.java:65)
[14:53:33 WARN]:        at AxInventoryRestore-1.2.2.jar//com.artillexstudios.axinventoryrestore.libs.gui.builder.item.BaseItemBuilder.asGuiItem(BaseItemBuilder.java:509)
[14:53:33 WARN]:        at AxInventoryRestore-1.2.2.jar//com.artillexstudios.axinventoryrestore.guis.MainGui.lambda$openMainGui$3(MainGui.java:59)
[14:53:33 WARN]:        at AxInventoryRestore-1.2.2.jar//com.artillexstudios.axinventoryrestore.database.DatabaseQueue.run(DatabaseQueue.java:51)
[14:53:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by BenceX100** [comment]
Should be fixed in v1.2.3
