### ISSUE TITLE
Luminol（Folia Fork）1.21 ERROR

### ISSUE THREAD

**Issue by x1aoren** [Artillex-Studios/AxInventoryRestore#22]
[21:19:15 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'AxInventoryRestore-3.2.3.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Error resolving libraries
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:552) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:294) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Error resolving libraries
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:117) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        ... 9 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at net.dv8tion:JDA:jar:5.0.0-beta.18
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:363) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:114) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        ... 9 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at net.dv8tion:JDA:jar:5.0.0-beta.18
        at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:260) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:328) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:114) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        ... 9 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for net.dv8tion:JDA:jar:5.0.0-beta.18
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:245) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.resolveCachedArtifactDescriptor(DfDependencyCollector.java:382) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.getArtifactDescriptorResult(DfDependencyCollector.java:368) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:218) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doCollectDependencies(DfDependencyCollector.java:108) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:222) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:328) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:114) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        ... 9 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: net.dv8tion:JDA:pom:5.0.0-beta.18 (absent): Could not transfer artifact net.dv8tion:JDA:pom:5.0.0-beta.18 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.236.0.15, repo.maven.apache.org/fd00:696e:6974:6578:0:0:94:10] failed: Connection refused: getsockopt
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:473) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:234) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.resolveCachedArtifactDescriptor(DfDependencyCollector.java:382) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.getArtifactDescriptorResult(DfDependencyCollector.java:368) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:218) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doCollectDependencies(DfDependencyCollector.java:108) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:222) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:328) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:114) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        ... 9 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact net.dv8tion:JDA:pom:5.0.0-beta.18 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.236.0.15, repo.maven.apache.org/fd00:696e:6974:6578:0:0:94:10] failed: Connection refused: getsockopt
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:44) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:417) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:537) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:234) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.resolveCachedArtifactDescriptor(DfDependencyCollector.java:382) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.getArtifactDescriptorResult(DfDependencyCollector.java:368) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:218) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doCollectDependencies(DfDependencyCollector.java:108) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:222) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:328) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:114) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        ... 9 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.236.0.15, repo.maven.apache.org/fd00:696e:6974:6578:0:0:94:10] failed: Connection refused: getsockopt
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.14.jar:4.5.14]
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:485) ~[maven-resolver-transport-http-1.9.18.jar:1.9.18]
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:435) ~[maven-resolver-transport-http-1.9.18.jar:1.9.18]
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:64) ~[maven-resolver-spi-1.9.18.jar:1.9.18]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:482) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:537) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:234) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.resolveCachedArtifactDescriptor(DfDependencyCollector.java:382) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.getArtifactDescriptorResult(DfDependencyCollector.java:368) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:218) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doCollectDependencies(DfDependencyCollector.java:108) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:222) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:328) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:114) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        ... 9 more
Caused by: java.net.ConnectException: Connection refused: getsockopt
        at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.14.jar:4.5.14]
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:485) ~[maven-resolver-transport-http-1.9.18.jar:1.9.18]
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:435) ~[maven-resolver-transport-http-1.9.18.jar:1.9.18]
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:64) ~[maven-resolver-spi-1.9.18.jar:1.9.18]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:482) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260) ~[maven-resolver-connector-basic-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:537) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:234) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175) ~[maven-resolver-provider-3.9.6.jar:3.9.6]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.resolveCachedArtifactDescriptor(DfDependencyCollector.java:382) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.getArtifactDescriptorResult(DfDependencyCollector.java:368) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:218) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doCollectDependencies(DfDependencyCollector.java:108) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:222) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:328) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:114) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.jar:1.21-DEV-a92cfa3]
        ... 9 more

**Comment by anmvc** [comment]
This is luminol's fault 100%. Just use regular folia

**Comment by BenceX100** [comment]
This is probably a damaged jar or something like that, definetly not a plugin issue, try redownloading it
