### ISSUE TITLE
folia error

### ISSUE THREAD

**Issue by cgw2023** [Artillex-Studios/AxInventoryRestore#6]
folia-bundler-1.20.2-R0.1-SNAPSHOT-reobf
AxInventoryRestore-1.4.1
```
[15:47:41 INFO]: [AxInventoryRestore] Enabling AxInventoryRestore v1.4.1
[15:47:41 ERROR]: Error occurred while enabling AxInventoryRestore v1.4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/dejvokep/boostedyaml/block/implementation/Section
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:247) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.artillexstudios.axinventoryrestore.config.impl.Config.setup(Config.java:21) ~[AxInventoryRestore-1.4.1.jar:?]
        at com.artillexstudios.axinventoryrestore.AxInventoryRestore.onEnable(AxInventoryRestore.java:76) ~[AxInventoryRestore-1.4.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.dejvokep.boostedyaml.block.implementation.Section
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 27 more
[15:47:41 INFO]: [AxInventoryRestore] Disabling AxInventoryRestore v1.4.1
[15:47:41 ERROR]: Error occurred (in the plugin loader) while disabling AxInventoryRestore v1.4.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.artillexstudios.axinventoryrestore.database.Database.cleanup()" because "com.artillexstudios.axinventoryrestore.AxInventoryRestore.database" is null
        at com.artillexstudios.axinventoryrestore.AxInventoryRestore.onDisable(AxInventoryRestore.java:112) ~[AxInventoryRestore-1.4.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"7aacf90"]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

**Comment by BenceX100** [comment]
Is there a libraries folder in the plugins/AxInventoryRestore folder? Also maybe try deleting it and restarting the server.

**Comment by cgw2023** [comment]
it seems like the bitdefender anti virus treated the file as a trojan, is this file safe?
![image](https://github.com/Artillex-Studios/AxInventoryRestore/assets/136877036/6e1f413b-7c09-4808-b3a1-2e43e19c2ca2)

**Comment by BenceX100** [comment]
Boostedyaml is an open source library that we use for the configuration files, antiviruses hate jars and it is probably a false detection.
